Display adresses on map
clairezed/guide-conso pull request #16
Opened 2018-06-12 19:18 UTC by clairezed

closes #8

2018-06-12 22:36 UTC, DavidBruant requested changes
Good overall
I'm marking request changes for the `.map`. The rest is more or less cosmetics

2018-06-12 22:36 UTC, DavidBruant commented on index.html
> +        <script crossorigin="anonymous" src='https://cdn.jsdelivr.net/npm/papaparse@4.5.0/papaparse.min.js'></script>
Interesting, i didn't know about this parser
My usual choice for a client-side csv parser is [d3-fetch csv function](https://github.com/d3/d3-fetch#csv), but this works too

2018-06-12 22:36 UTC, DavidBruant commented on index.js
> +const guideMap = L.map('mapid', {
Nice rename!

2018-06-12 22:36 UTC, DavidBruant commented on index.js
> +	download: true,
The indent looks weird here

2018-06-12 22:36 UTC, DavidBruant commented on index.js
> +    addresses.map(address => {
`.map` does what is intended, but is usually used to create another array
If you want to only iterate over the array, you may prefer `.forEach`. A [for-of loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#Examples) works too

2018-06-12 22:36 UTC, DavidBruant commented on index.js
> +        let long = address['Longitude'];
if you don't intend to change the variable value, prefer `const` to `let`

2018-06-12 22:36 UTC, DavidBruant commented on index.js
> +        let long = address['Longitude'];
Another option here is to use [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring)
```js
const {Latitude: lat, Longitude : long} = address;
```

2018-06-12 22:36 UTC, DavidBruant commented on index.js
> +        console.log(error);
The [console object](https://developer.mozilla.org/en-US/docs/Web/API/Console) has lots of methods including one dedicated to showing a message as an error in the console : `console.error`

2018-06-12 22:36 UTC, DavidBruant commented on index.js
>      accessToken: 'your.mapbox.access.token'
The token is provided in the url above, so this line can be removed i think
(sorry i didn't catch it earlier)

2018-06-13 16:09 UTC, clairezed commented on index.js
> +        let long = address['Longitude'];
yeah ! yeah ! Have never used destructuring yet ! Let's do that !

2018-06-13 17:17 UTC, clairezed commented
Je te laisse jeter un oeil et merger si ça te convient ?

2018-06-14 09:10 UTC, DavidBruant commented on index.html
> +        <div id="mapid" class="map-container"></div>
You don't need the id if you have the class

2018-06-14 09:10 UTC, DavidBruant commented on index.js
> +const guideMap = L.map('mapid', {
instead of the id (because you'll remove it), you can pass the DOM element directly

2018-06-14 09:10 UTC, DavidBruant commented
LGTM modulo l'histoire de l'id

2018-06-14 09:24 UTC, clairezed commented
Damned, I've been writing French in my last comment, sorry for that. 

I've replaced map `id` with `data-attribute`, so as to separate style with js selector.

2018-06-14 09:24 UTC, DavidBruant commented on index.js
> +const mapElement = document.querySelector('[data-map="main"]')
pourquoi pas `document.querySelector('.map-container')` ?

2018-06-14 09:26 UTC, DavidBruant commented
oh i've been writing french as well, sorry :-/
i'm having a hard time switching back and forth between French and English in different repos
Is it ok for you if we write the language we choose in the infusion file?

2018-06-14 09:28 UTC, clairezed commented on index.js
> +const mapElement = document.querySelector('[data-map="main"]')
To separate css style with js selector. I took this habit in my previous agency, it saved our lives a few time : style may change, css classes may change, and it shouldn't impact js.

2018-06-14 09:33 UTC, DavidBruant commented on index.js
> +const mapElement = document.querySelector('[data-map="main"]')
interesting... i'm not sure i agree, but that's fine in our case
PR can be merged :-)

2018-06-14 09:36 UTC, DavidBruant approved these changes

2018-06-14 09:36 UTC, merged