Es lint
clairezed/guide-conso pull request #19
Opened 2018-06-18 14:26 UTC by clairezed

Add two eslint config files for the project : 
- one general
- one for appscripts 

I hope hierarchical configuration (https://eslint.org/docs/user-guide/configuring#using-configuration-files) is enough to override general config in appscripts directory (not clear to me). We'll see.

2018-06-18 21:10 UTC, DavidBruant requested changes
Requesting changes because of duplication

2018-06-18 21:10 UTC, DavidBruant commented on .eslintrc.yml
> +    - tab
this is inconsistent with the other file

`<troll>`do you prefer tabs?`</troll>`

2018-06-18 21:10 UTC, DavidBruant commented on appscripts/.eslintrc.yml
> +  onFormSubmitTrigger: false
Hey! Look what i've found! 
https://github.com/selectnull/eslint-plugin-googleappsscript

2018-06-18 21:10 UTC, DavidBruant commented on appscripts/.eslintrc.yml
> +    - always
I feel like most of what's written here is redundant with what's in the other file.
If cascading works, this shouldn't be necessary

2018-06-18 21:10 UTC, DavidBruant commented on appscripts/.eslintrc.yml
> +  browser: true
Because the above file has `es6: true`, i feel `es6: false` should be written here

Maybe even something related to `parserOptions` with an explicit 5 (ou 3?)

2018-06-18 21:10 UTC, DavidBruant commented on index.js
> -	error: function (error, file) {
:+1: <3 eslint

2018-06-18 21:10 UTC, DavidBruant commented on index.js
> +	for(let address of addresses){
if you don't plan on modifying `address`, you can even choose `const`

2018-06-18 21:12 UTC, DavidBruant commented
> Add two eslint config files for the project :

Another option is to have a single file and use the `overrides` key: https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns

> I hope hierarchical configuration (https://eslint.org/docs/user-guide/configuring#using-configuration-files) is enough to override general config in appscripts directory (not clear to me). We'll see.

Have you tested that it does override the way you want it to? :-p 
Maybe you should ;-)

2018-06-18 21:13 UTC, DavidBruant commented
One more thing, maybe you should create an npm script (like `npm run lint`) and add eslint to the dev-dependencies. This way, people installing your project have all the necessary tooling.

Maybe add a note in the readme about that as well

2018-06-19 13:09 UTC, clairezed commented on appscripts/.eslintrc.yml
> +  onFormSubmitTrigger: false
\o/ (Note to myself : get the habit to look for specific plugins)

2018-06-19 13:27 UTC, clairezed commented on appscripts/.eslintrc.yml
> +  browser: true
Seems to be "close to" es5 (https://en.wikipedia.org/wiki/Google_Apps_Script), let's go for it then ?

2018-06-19 13:43 UTC, DavidBruant commented on appscripts/.eslintrc.yml
> +  browser: true
to my knowledge, the only practical difference between ES5 and ES3 in syntax is getters and setters. Can you try to see if they work in GAS? This way, we'll know what to choose for sure

2018-06-19 14:04 UTC, clairezed commented
> Another option is to have a single file and use the overrides key: https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns 

The use case for `override` given in the docs is *"for example if the configuration for files within the same directory has to be different"*. And actually, I indeed feel more comfortable with adding another config file at the root of a directory rather than using `override`. It seems more 'resilient' to me (if I have to reorganize my directories in my project folder, for instance)

> Have you tested that it does override the way you want it to? :-p

Manual test only :) (if you have another way to test in mind, please share it !). Actually, it is not cascading, and there were no code duplication : eslint simply uses the closest config file. Therefore, I have to repeat rules I want to apply in every directory, but I don't have to negate rules used in root directory that I don't want in a specific folder.

2018-06-19 14:16 UTC, clairezed commented on appscripts/.eslintrc.yml
> +  browser: true
I used a piece of code found [here](https://javascriptplayground.com/es5-getters-setters/), getters and setters seem to work

2018-06-19 14:32 UTC, DavidBruant commented on package.json
> +    "lint": "eslint . --ext .js; exit 0",
I'm surprised about the `--ext .js` and `exit 0`
Why is each needed?

2018-06-19 14:39 UTC, DavidBruant commented
> actually, I indeed feel more comfortable with adding another config file at the root of a directory rather than using override. It seems more 'resilient' to me (if I have to reorganize my directories in my project folder, for instance)

Sounds good :+1: 

> Actually, it is not cascading

This conclusion goes against what i understand of [the related documentation](https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy):

> When ESLint traverses into the tests/ directory, it will then use your-project/tests/.eslintrc in addition to your-project/.eslintrc. So your-project/tests/test.js is linted based on the combination of the two .eslintrc files in its directory hierarchy

What do you understand of this doc? Do you feel like there is a contradiction as well?

> Manual test only :) (if you have another way to test in mind, please share it !)

Nah, manual testing, nothing better, sorry :-)

2018-06-19 15:24 UTC, clairezed commented on package.json
> +    "lint": "eslint . --ext .js; exit 0",
I was looking for a way to have eslint check every `*.js` files in the whole directory, hence ` --ext .js`. I guess I found a way to make my life complicated with no reason.

And `eslint . --ext .js``worked perfectly in command line, but `npm run lint` (with this exact command) provoked an error : 
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
My searches lead me to https://github.com/eslint/eslint/issues/2409#issuecomment-103768546, hence `; exit 0`

2018-06-19 15:30 UTC, DavidBruant commented on package.json
> +    "lint": "eslint . --ext .js; exit 0",
> I was looking for a way to have eslint check every *.js files in the whole directory, hence --ext .js. I guess I found a way to make my life complicated with no reason.

I think `eslint . --fix` does the job fine here

> but npm run lint (with this exact command) provoked an error

oh, interesting!
One option is to do `npm run lint -s`, this way, you'll only see the lint errors and not the npm error. But `; exit 0` is fine too

2018-06-19 15:38 UTC, clairezed commented on package.json
> +    "lint": "eslint . --ext .js; exit 0",
Couldn't running `eslint . --fix` be "dangerous" ?

2018-06-19 15:42 UTC, DavidBruant commented on package.json
> +    "lint": "eslint . --ext .js; exit 0",
dangerous to whom? in what way?

2018-06-19 15:43 UTC, DavidBruant commented on package.json
> +    "lint": "eslint . --ext .js; exit 0",
(comment j'me la raconte de trop en utilisant "whom" :-p)

2018-06-19 16:53 UTC, clairezed commented on package.json
> +    "lint": "eslint . --ext .js; exit 0",
in automatically fixing lots of things without a preliminary human check ? 
I thought `npm run lint` was to make an "audit", not to fix automatically 

PS : oué tu te la racontes graaaave

2018-06-19 17:06 UTC, DavidBruant commented on package.json
> +    "lint": "eslint . --ext .js; exit 0",
oh ok, yes, sorry, my mistake on the `--fix`
I think it's okay, because eslint is run before commiting, so you have an occasion to see the changes performes by ESLint before commiting, but it's ok to do with and without `--fix` in different phases

2018-06-19 17:23 UTC, clairezed commented
> This conclusion goes against what i understand of the related documentation:

weird. I understand the same thing as you do, but my manual experiments proved me the contrary. 

[... another micro test later]

Ok, I think I got it. There was in appscripts directory a `extends: 'eslint:recommended'` that was overriding the root config. Now, I can observe the cascading.

If it's ok with you, could you approve this PR ?

2018-06-20 14:03 UTC, clairezed commented
I begin a huge session of mergin' without review, as I have right now too many unsynchronized branches.

Is it possible to review afterwards ?

2018-06-20 14:04 UTC, merged